### PR TITLE
updated plots for big bend trends paper

### PR DESCRIPTION
**Pull request by jennmoore924**
fixed scale of plots (unlogged transect length)

### CODE REVIEW

**Comment by melimore86** [comment]
Would you like me to review?

**Comment by billpine** [comment]
Yes

On Sep 10, 2019, at 6:12 PM, Mel M <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL EMAIL: Exercise caution with links and attachments.




Would you like me to review?

**Comment by melimore86** [comment]
Reviewed graphs, text is correct and accurate. Do you need the figures to be in colorblind colors (i.e not using red and green)?

**Comment by billpine** [comment]
Good idea. Tips?

On Sep 10, 2019, at 7:00 PM, Mel M <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL EMAIL: Exercise caution with links and attachments.




Reviewed graphs, text is correct and accurate. Do you need the figures to be in colorblind colors (i.e not using red and green)?

**Comment by melimore86** [comment]
I usually use the colors in this link:

**Pull request merged**
