### PR TITLE
June 14 2019 transect data added

### PR DESCRIPTION
**Pull request by sbeck1**

### CODE REVIEW

**Comment by billpine** [comment]
Steve, Mel and I reviewed the pull request. There is an error in the dates for one of the files. See the "raw data check" tab.  Thanks.

**Comment by sbeck1** [comment]
Yes I found this as I was prepping for the next round of data entry.  My next pull request will have this fixed, plus additional transect data.  In field now and much of this week.  I will likely not get to this until later this week.
________________________________________

**Comment by billpine** [comment]
OK keep me posted on the data entry. Also add me as a reviewer when you submit something as Mel missed this. She and I went over it and we will both be watching for changes. Thanks for working on this, good luck in the field.

**Comment by billpine** [comment]
I think this needs to be done as a new (regular) pull request and not attached to this comment?

**Comment by billpine** [comment]
Just spoke with Steve about this. Will close this comment.

**Pull request closed without merging**
